###getBill
GET http://localhost:8080/bill/nowak1212

###Create User
POST http://localhost:8080/user
Content-Type: application/json

{
  "login": "OBR_user2",
  "firstName": "Jan",
  "lastName": "Kowalski",
  "attrType": "account",
  "attrContent": "123456789012344478912123459"
}
###Create User
POST http://localhost:8080/user
Content-Type: application/json

{
  "login": "OBR_user3",
  "firstName": "Marian",
  "lastName": "Kowalski",
  "attrType": "account",
  "attrContent": "12345678901234447890123436"
}
###Create User
POST http://localhost:8080/user
Content-Type: application/json

{
  "login": "OBR_user4",
  "firstName": "Marian",
  "lastName": "Nowak",
  "attrType": "account",
  "attrContent": "12345678901233447890125456"
}



###Create Bill
POST http://localhost:8080/bill
Content-Type: application/json

{
  "description": "Obr_1",
  "price": 780,
  "groupName": "Obrona",
  "loginPayer": "OBR_user2"
}

###getBillDetail
GET http://localhost:8080/billDetail/
Content-Type: application/json

{
  "loginBorrower": "OBR_user4",
  "groupName": "Obrona"
}

###Update Bill
PUT http://localhost:8080/bill/14
Content-Type: application/json

{
  "price": 300

}

###Delete Bill
DELETE http://localhost:8080/bill/10


###Get All Bill
GET http://localhost:8080/bill

###Update Bill Details
PUT http://localhost:8080/billDetail/34
Content-Type: application/json

{
  "amount": 23
}

###Get All Group
GET http://localhost:8080/group

###Create Group
POST http://localhost:8080/group
Content-Type: application/json

{
  "groupName": "Obrona",
  "login": "OBR_user2"
}

###Update Group
PUT http://localhost:8080/group/4
Content-Type: application/json

{
  "name": "PrezentyM"
}
###Delete Group
DELETE http://localhost:8080/group/10


